import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "welcome",
      label: "👋 Welcome",
    },
    {
      type: "doc",
      id: "getting-started",
      label: "Getting Started",
    },
    {
      type: "doc",
      id: "create-token",
      label: "Creating a Token",
    },
    {
      type: "doc",
      id: "user-xp-and-leadingboard",
      label: "User XP and Leaderboard",
    },
    {
      type: "doc",
      id: "bonding-curve",
      label: "Bonding Curve",
    },
    {
      type: "doc",
      id: "market-cap",
      label: "Market Cap",
    },
    {
      type: "doc",
      id: "understanding-the-trade-chart",
      label: "Understanding the Trade Chart",
    },
    {
      type: "doc",
      id: "legend-token",
      label: "Legend Token",
    },
    {
      type: "doc",
      id: "not-og-and-cto-token",
      label: "Not OG and CTO Token",
    },
  ],
};

export default sidebars;
