import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "lync",
      label: "👋 Introducing LYNC",
    },
    {
      type: "category",
      label: "products",
      collapsed: false,
      items: [
        "lync/products/lync-account-abstraction-sdk",
        "lync/products/lync-account-abstraction-webgl-sdk",
        "lync/products/metamask-wallet",
        "lync/products/lync-metamask-pc-sdk",
        "lync/products/okx-wallet",
        "lync/products/lync-in-game-marketplace-sdk",
        "lync/products/nft-fetcher",
        "lync/products/no-code-smart-contract-deployer",
        {
          type: "category",
          label: "EVM Lootbox SDK",
          link: {
            type: "doc",
            id: "lync/products/evm-lootbox-sdk/evm-lootbox-sdk",
          },
          items: [
            "lync/products/evm-lootbox-sdk/getting-started",
            {
              type: "category",
              label: "Using the SDK",
              link: {
                type: "doc",
                id: "lync/products/evm-lootbox-sdk/using-the-sdk/evm-lootbox-sdk-using-sdk",
              },
              items: [
                "lync/products/evm-lootbox-sdk/using-the-sdk/creating-a-new-lootbox",
                "lync/products/evm-lootbox-sdk/using-the-sdk/opening-a-lootbox",
                "lync/products/evm-lootbox-sdk/using-the-sdk/claiming-rewards",
                "lync/products/evm-lootbox-sdk/using-the-sdk/whitelisting-users-using-lootbox",
                "lync/products/evm-lootbox-sdk/using-the-sdk/lootbox-admin-functions",
                "lync/products/evm-lootbox-sdk/using-the-sdk/useful-information-functions-from-lynclootbox-class",
                "lync/products/evm-lootbox-sdk/using-the-sdk/multicall-opening-and-claiming-multiple-lootboxes-in-a-single-transaction",
              ],
            },
            {
              type: "category",
              label: "Example Codes in React & TypeScript",
              link: {
                type: "doc",
                id: "lync/products/evm-lootbox-sdk/example-codes-in-react-and-typescript/evm-lootbox-sdk-example-codes",
              },
              items: [
                "lync/products/evm-lootbox-sdk/example-codes-in-react-and-typescript/example-code-for-creating-a-new-lootbox",
                "lync/products/evm-lootbox-sdk/example-codes-in-react-and-typescript/example-code-for-opening-a-lootbox",
                "lync/products/evm-lootbox-sdk/example-codes-in-react-and-typescript/example-code-for-claiming-a-lootbox",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Launch your products on Telegram",
          link: {
            type: "doc",
            id: "lync/products/launch-your-products-on-telegram/telegram-launch",
          },
          items: [
            "lync/products/launch-your-products-on-telegram/configure-your-telegram-bot",
            "lync/products/launch-your-products-on-telegram/deploying-your-product-on-tg",
          ],
        },
      ],
    },
    // {
    //   type: 'doc',
    //   id: 'graphql-example',
    //   label:'GraphQL Example'
    // },
    {
      type: "category",
      label: "aptos",
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items: [
        {
          type: "category",
          label: "LYNC Paymaster - Supporting aptos",
          link: {
            type: "doc",
            id: "lync/aptos/lync-paymaster-supporting-aptos/lync-paymaster-supporting-aptos",
          },
          items: [
            "lync/aptos/lync-paymaster-supporting-aptos/how-to-register-on-lync-dashboard",
            "lync/aptos/lync-paymaster-supporting-aptos/how-to-create-paymaster",
            "lync/aptos/lync-paymaster-supporting-aptos/how-to-fund-the-paymaster",
            "lync/aptos/lync-paymaster-supporting-aptos/module-and-function-whitelist",
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                "lync/aptos/lync-paymaster-supporting-aptos/how-to-integrate-paymaster/unity",
                "lync/aptos/lync-paymaster-supporting-aptos/how-to-integrate-paymaster/api",
                "lync/aptos/lync-paymaster-supporting-aptos/how-to-integrate-paymaster/javascript-typescript",
              ],
            },
          ],
        },
        "lync/aptos/lync-unity-aptos-sdk",
        {
          type: "category",
          label: "Keyless Accounts",
          link: {
            type: "doc",
            id: "lync/aptos/keyless-accounts/keyless-accounts",
          },
          items: [
            "lync/aptos/keyless-accounts/configure-your-oidc-provider",
            "lync/aptos/keyless-accounts/integrate-keyless-in-unity",
          ],
        },
        {
          type: "category",
          label: "Wallet Creation and Transaction APIs",
          link: {
            type: "doc",
            id: "lync/aptos/wallet-creation-and-transaction-apis/wallet-creation-and-transaction-apis",
          },
          items: [
            "lync/aptos/wallet-creation-and-transaction-apis/pre-requisites",
            {
              type: "category",
              label: "Integration",
              link: {
                type: "doc",
                id: "lync/aptos/wallet-creation-and-transaction-apis/integration/integration",
              },
              items: [
                "lync/aptos/wallet-creation-and-transaction-apis/integration/api-overview",
                "lync/aptos/wallet-creation-and-transaction-apis/integration/create-a-new-wallet",
                "lync/aptos/wallet-creation-and-transaction-apis/integration/get-already-created-wallet",
                "lync/aptos/wallet-creation-and-transaction-apis/integration/mint-nft-transactions",
                "lync/aptos/wallet-creation-and-transaction-apis/integration/send-generic-transactions-on-aptos",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "LYNC Social Login SDK on aptos",
          link: {
            type: "doc",
            id: "lync/aptos/lync-social-login-sdk-on-aptos/lync-social-login-sdk-on-aptos",
          },
          items: [
            "lync/aptos/lync-social-login-sdk-on-aptos/getting-started",
            "lync/aptos/lync-social-login-sdk-on-aptos/using-the-sdk",
            "lync/aptos/lync-social-login-sdk-on-aptos/example-codes-in-react-and-typescript",
            "lync/aptos/lync-social-login-sdk-on-aptos/types-used-in-the-methods-provided-by-the-sdk",
            "lync/aptos/lync-social-login-sdk-on-aptos/other-specification",
          ],
        },
        {
          type: "category",
          label: "LYNC aptos Lootbox",
          link: {
            type: "doc",
            id: "lync/aptos/lync-aptos-lootbox/lync-aptos-lootbox",
          },
          items: [
            "lync/aptos/lync-aptos-lootbox/getting-started",
            "lync/aptos/lync-aptos-lootbox/creating-a-lootbox",
            "lync/aptos/lync-aptos-lootbox/opening-a-lootbox",
            "lync/aptos/lync-aptos-lootbox/claiming-the-rewards",
            "lync/aptos/lync-aptos-lootbox/conclusion",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Movement Labs",
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items: [
        // {
        //   type: 'category',
        //   label:'📇 Indexer',
        //   link:{
        //     type: 'doc',
        //     id:'MOVEMENT/indexer/movement-indexer'
        //   },
        //   items:[
        //     'MOVEMENT/indexer/movement-indexer-how-to-run',
        //     {
        //       type:'category',
        //       label:'Example Queries',
        //       items:[
        //         'MOVEMENT/indexer/examples/movement-indexer-example-1',
        //         'MOVEMENT/indexer/examples/movement-indexer-example-2',
        //         'MOVEMENT/indexer/examples/movement-indexer-example-3',
        //       ]
        //     }
        //   ]
        // },
        "lync/movement-labs/nft-deployer/nft-deployer",
        {
          type: "category",
          label: "LYNC Social Login SDK on Movement",
          link: {
            type: "doc",
            id: "lync/movement-labs/lync-social-login-sdk-on-movement/lync-social-login-sdk-on-movement",
          },
          items: [
            "lync/movement-labs/lync-social-login-sdk-on-movement/getting-started",
            "lync/movement-labs/lync-social-login-sdk-on-movement/using-the-sdk",
            "lync/movement-labs/lync-social-login-sdk-on-movement/example-codes-in-react-and-typescript",
            "lync/movement-labs/lync-social-login-sdk-on-movement/types-and-enums-used-in-the-methods-provided-by-the-sdk",
            "lync/movement-labs/lync-social-login-sdk-on-movement/other-specification",
          ],
        },
        "lync/movement-labs/lync-unity-movement-sdk",
        {
          type: "category",
          label: "Wallet Creation and Transaction APIs",
          link: {
            type: "doc",
            id: "lync/movement-labs/wallet-creation-and-transaction-apis/wallet-creation-and-transaction-apis",
          },
          items: [
            "lync/movement-labs/wallet-creation-and-transaction-apis/pre-requisites",
            {
              type: "category",
              label: "Integration",
              link: {
                type: "doc",
                id: "lync/movement-labs/wallet-creation-and-transaction-apis/integration/integration",
              },
              items: [
                "lync/movement-labs/wallet-creation-and-transaction-apis/integration/api-overview",
                "lync/movement-labs/wallet-creation-and-transaction-apis/integration/create-a-new-wallet",
                "lync/movement-labs/wallet-creation-and-transaction-apis/integration/get-already-created-wallet",
                "lync/movement-labs/wallet-creation-and-transaction-apis/integration/mint-nft-transactions",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "LYNC Paymaster - Supporting Movement",
          link: {
            type: "doc",
            id: "lync/movement-labs/lync-paymaster-supporting-movement/lync-paymaster-supporting-movement",
          },
          items: [
            "lync/movement-labs/lync-paymaster-supporting-movement/how-to-register-on-lync-dashboard",
            "lync/movement-labs/lync-paymaster-supporting-movement/how-to-create-paymaster",
            "lync/movement-labs/lync-paymaster-supporting-movement/how-to-fund-the-paymaster",
            "lync/movement-labs/lync-paymaster-supporting-movement/module-and-function-whitelist",
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                "lync/movement-labs/lync-paymaster-supporting-movement/how-to-integrate-paymaster/javascript-typescript",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SUPRA",

      items: [
        {
          type: "category",
          label: "LYNC Paymaster - Supporting Supra L1",
          link: {
            type: "doc",
            id: "lync/supra/lync-paymaster-supporting-supra-l1/lync-paymaster-supporting-supra-l1",
          },
          items: [
            "lync/supra/lync-paymaster-supporting-supra-l1/how-to-register-on-lync-dashboard",
            "lync/supra/lync-paymaster-supporting-supra-l1/how-to-create-paymaster",
            "lync/supra/lync-paymaster-supporting-supra-l1/how-to-fund-the-paymaster",
            "lync/supra/lync-paymaster-supporting-supra-l1/module-and-function-whitelist",
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                "lync/supra/lync-paymaster-supporting-supra-l1/how-to-integrate-paymaster/javascript-typescript",
              ],
            },
          ],
        },
        "lync/supra/lync-unity-supra-sdk",
        {
          type: "category",
          label: "Wallet Creation and Transaction APIs",
          link: {
            type: "doc",
            id: "lync/supra/wallet-creation-and-transaction-apis/wallet-creation-and-transaction-apis",
          },
          items: [
            "lync/supra/wallet-creation-and-transaction-apis/pre-requisites",
            {
              type: "category",
              label: "Integration",
              link: {
                type: "doc",
                id: "lync/supra/wallet-creation-and-transaction-apis/integration/integration",
              },
              items: [
                "lync/supra/wallet-creation-and-transaction-apis/integration/api-overview",
                "lync/supra/wallet-creation-and-transaction-apis/integration/create-a-new-wallet",
                "lync/supra/wallet-creation-and-transaction-apis/integration/get-already-created-wallet",
                "lync/supra/wallet-creation-and-transaction-apis/integration/mint-nft-transactions",
              ],
            },
          ],
        },
        // {
        //   type:'category',
        //   label:'Wallet Creation and Transaction APIs',
        //   link:{
        //     type: 'doc',
        //     id:'FUEL/wallet-apis/fuel-wallet'
        //   },
        //   items:[

        //     'FUEL/wallet-apis/prerequisites/prerequisites',
        //     {
        //       type:'category',
        //       label:'Integration',
        //       link:{
        //         type: 'doc',
        //         id:'FUEL/wallet-apis/integration/integration'
        //       },
        //       items:[
        //         'FUEL/wallet-apis/integration/feat/fuel-overview',
        //         'FUEL/wallet-apis/integration/feat/fuel-create-wallet',
        //         'FUEL/wallet-apis/integration/feat/fuel-get-created-wallet',

        //       ]
        //     }

        //   ],

        // }
      ],
    },
    {
      type: "category",
      label: "FUEL",
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items: [
        "lync/fuel/lync-unity-fuel-sdk",
        {
          type: "category",
          label: "LYNC NFT Deployer",
          link: {
            type: "doc",
            id: "lync/fuel/lync-nft-deployer/lync-nft-deployer",
          },
          items: [
            "lync/fuel/lync-nft-deployer/introduction",
            "lync/fuel/lync-nft-deployer/getting-started",
            {
              type: "category",
              label: "Deploying Your NFTs",
              link: {
                type: "doc",
                id: "lync/fuel/lync-nft-deployer/deploying-your-nfts/deploying-your-nfts",
              },
              items: ["lync/fuel/lync-nft-deployer/deploying-your-nfts/launch-your-entire-collection"],
            },
            "lync/fuel/lync-nft-deployer/troubleshooting-and-faqs",
          ],
        },
        {
          type: "category",
          label: "LYNC Fuel Lootbox",
          link: {
            type: "doc",
            id: "lync/fuel/lync-fuel-lootbox/lync-fuel-lootbox",
          },
          items: [
            "lync/fuel/lync-fuel-lootbox/getting-started",
            "lync/fuel/lync-fuel-lootbox/creating-a-lootbox",
            "lync/fuel/lync-fuel-lootbox/opening-a-lootbox",
            "lync/fuel/lync-fuel-lootbox/claiming-the-rewards",
            "lync/fuel/lync-fuel-lootbox/conclusion",
          ],
        },
        {
          type: "category",
          label: "Wallet Creation and Transaction APIs",
          link: {
            type: "doc",
            id: "lync/fuel/wallet-creation-and-transaction-apis/wallet-creation-and-transaction-apis",
          },
          items: [
            "lync/fuel/wallet-creation-and-transaction-apis/pre-requisites",
            {
              type: "category",
              label: "Integration",
              link: {
                type: "doc",
                id: "lync/fuel/wallet-creation-and-transaction-apis/integration/integration",
              },
              items: [
                "lync/fuel/wallet-creation-and-transaction-apis/integration/api-overview",
                "lync/fuel/wallet-creation-and-transaction-apis/integration/create-a-new-wallet",
                "lync/fuel/wallet-creation-and-transaction-apis/integration/get-already-created-wallet",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Fuel Marketplace NPM SDK",
          link: {
            type: "doc",
            id: "lync/fuel/fuel-marketplace-npm-sdk/fuel-marketplace-npm-sdk",
          },
          items: [
            "lync/fuel/fuel-marketplace-npm-sdk/getting-started",
            {
              type: "category",
              label: "Using the SDK",
              link: {
                type: "doc",
                id: "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/using-the-sdk",
              },
              items: [
                "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/using-hooks-to-get-the-marketplace-data",
                "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/using-services-provided-by-the-sdk-to-list-buy-and-manage-tokens",
                "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/some-useful-functions-provided-by-the-sdk",
                "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/error-codes-for-the-sdk",
                "lync/fuel/fuel-marketplace-npm-sdk/using-the-sdk/interfaces-and-enums-provided-by-the-sdk",
              ],
            },
            "lync/fuel/fuel-marketplace-npm-sdk/support",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "METIS",
      items: [
        {
          type: "category",
          label: "Wallet Creation and Transaction APIs",
          link: {
            type: "doc",
            id: "lync/metis/wallet-creation-and-transaction-apis/wallet-creation-and-transaction-apis",
          },
          items: [
            "lync/metis/wallet-creation-and-transaction-apis/pre-requisites",
            {
              type: "category",
              label: "Integration",
              link: {
                type: "doc",
                id: "lync/metis/wallet-creation-and-transaction-apis/integration/integration",
              },
              items: [
                "lync/metis/wallet-creation-and-transaction-apis/integration/api-overview",
                "lync/metis/wallet-creation-and-transaction-apis/integration/create-a-new-wallet",
                "lync/metis/wallet-creation-and-transaction-apis/integration/get-already-created-wallet",
                "lync/metis/wallet-creation-and-transaction-apis/integration/mint-nft-transactions",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "NPM PACKAGES",
      items: [
        {
          type: "category",
          label: "Marketplace",
          link: {
            type: "doc",
            id: "lync/npm-packages/marketplace/marketplace",
          },
          items: [
            "lync/npm-packages/marketplace/hook-useallcollectionnft",
            "lync/npm-packages/marketplace/hook-useallbuynft",
            "lync/npm-packages/marketplace/hook-useallownernft",
            "lync/npm-packages/marketplace/hook-usenftdetails",
            "lync/npm-packages/marketplace/hook-useallnftforrent",
          ],
        },
        {
          type: "category",
          label: "Metamask Wallet SDK",
          link: {
            type: "doc",
            id: "lync/npm-packages/metamask-wallet-sdk/metamask-wallet-sdk",
          },
          items: [
            "lync/npm-packages/metamask-wallet-sdk/metamask-wallet-sdk-getting-started",
            {
              type: "category",
              label: "Using the SDK",
              link: {
                type: "doc",
                id: "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk",
              },
              items: [
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-wrapping-your-application",
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-handle-wallet-connections.md",
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-manage-networks",
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-native-currency-balance",
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-using-wallet-and-signer",
                "lync/npm-packages/metamask-wallet-sdk/using-the-sdk/metamask-wallet-sdk-using-the-sdk-types",
              ],
            },
            "lync/npm-packages/metamask-wallet-sdk/metamask-wallet-sdk-supported-chains",
            "lync/npm-packages/metamask-wallet-sdk/metamask-wallet-sdk-support",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
